config/routes.rb
TestTask::Application.routes.draw do

  devise_for :users
  devise_scope :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  get "user/dashboard"

  devise_for :users
  root :to => 'user#landing'

  get "service/twitter"
  get "service/facebook"
  get "service/twitter_return"

  match '/auth/twitter/callback' => 'service#twitter_return'
  match '/auth/facebook/callback' => 'service#facebook_return'
  post "service/twitter" => "service#block"
  post "service/facebook" => "service#like"
  post "service/facebook" => "service#reply"
  post "service/facebook" => "service#delete_post"

end

app/models/facebook_account.rb
class FacebookAccount < ActiveRecord::Base
 
  # Stubbed out! Does no (good) error checking!  
 
  # Get these from facebook!
  FACEBOOK_CLIENT_ID = 'it'
  FACEBOOK_CLIENT_SECRET = 'secret'
 
  def authorize_url(callback_url = '')
    if self.oauth_authorize_url.blank?
      self.oauth_authorize_url = "https://graph.facebook.com/oauth/authorize?client_id=#{FACEBOOK_CLIENT_ID}&redirect_uri=#{callback_url}&scope=offline_access,publish_stream"
      self.save!
    end
    self.oauth_authorize_url
  end
  
  def validate_oauth_token(oauth_verifier, callback_url = '')
    response = RestClient.get 'https://graph.facebook.com/oauth/access_token', :params => {
                   :client_id => FACEBOOK_CLIENT_ID,
                   :redirect_uri => callback_url.html_safe,
                   :client_secret => FACEBOOK_CLIENT_SECRET,
                   :code => oauth_verifier.html_safe
                }
    pair = response.body.split("&")[0].split("=")
    if (pair[0] == "access_token")
      self.access_token = pair[1]
      response = RestClient.get 'https://graph.facebook.com/me', :params => { :access_token => self.access_token }
      self.stream_url = JSON.parse(response.body)["link"]
      self.active = true
    else 
      self.errors.add(:oauth_verifier, "Invalid token, unable to connect to facebook: #{pair[1]}")
      self.active = false
    end
    self.save!
  end
  
  def post(message)
    RestClient.post 'https://graph.facebook.com/me/feed', { :access_token => self.access_token, :message => message }
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/facebook_accounts_controller.rb
class FacebookAccountsController < ApplicationController
 
  # Stubbed out! Does no (good) error checking!
 
  def new
    facebook_account = FacebookAccount.create()
    redirect_to(facebook_account.authorize_url(facebook_callback_url(:id => facebook_account.id)))
  end
 
  def callback
    if params[:error_reason] && !params[:error_reason].empty?
      # We have a problem!
      redirect_to(:root, :notice => "Unable to activate facebook: #{params[:error_reason]}")
    elsif params[:code] && !params[:code].empty?
      # This is the callback, we have an id and an access code
      facebook_account = FacebookAccount.find(params[:id])
      facebook_account.validate_oauth_token(params[:code], facebook_callback_url(:id => facebook_account.id))
      redirect_to(:root, :notice => 'Facebook account activated!')
    end
  end
 
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController

  before_filter :authenticate_user!

  def twitter
   	@twitter = Twitter.user_timeline('pallavi_shastry', :count => 10)
  end

  def twitter_return
  	redirect_to :controller => "service", :action => "twitter"
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new('CAACEdEose0cBAAVfXNZAkgAZAqSqZAPRJy0WqvxSauqfZCu6DMapylTDE5AgzNFpGIqGhsTknt0YP1OGdejvWnxs6Eqo1wPZAZBD2BXKbXLrvEFZCqNdGPJLs4lza2XXDuD0EP9I81NAlWXTCP94qWK2E5QcHjSxLLiWSR2gvL4tQZDZD')  
    @results = @facebook.get_connections("me", "posts")
    link = t.first['link']
    @friends = @facebook.fql_query("SELECT friend_count FROM user WHERE uid = me()")
  end

  def block
    @name = params[:q]
    Twitter.block(@name)
    flash[:notice] = "Blocked"
    redirect_to :controller => "service", :action => "twitter"
  end

  def like
    @facebook ||= Koala::Facebook::API.new('CAACEdEose0cBAAVfXNZAkgAZAqSqZAPRJy0WqvxSauqfZCu6DMapylTDE5AgzNFpGIqGhsTknt0YP1OGdejvWnxs6Eqo1wPZAZBD2BXKbXLrvEFZCqNdGPJLs4lza2XXDuD0EP9I81NAlWXTCP94qWK2E5QcHjSxLLiWSR2gvL4tQZDZD')  
    @id = params[:post_id]
    @facebook.put_like(@id)
    redirect_to :controller => "service", :action => "facebook"
  end

  def reply
    @facebook ||= Koala::Facebook::API.new('CAACEdEose0cBAAVfXNZAkgAZAqSqZAPRJy0WqvxSauqfZCu6DMapylTDE5AgzNFpGIqGhsTknt0YP1OGdejvWnxs6Eqo1wPZAZBD2BXKbXLrvEFZCqNdGPJLs4lza2XXDuD0EP9I81NAlWXTCP94qWK2E5QcHjSxLLiWSR2gvL4tQZDZD')  
    @id = params[:post_id]
    @reply_message = params[:reply_message]
    @facebook.put_comment(@id,@reply_message)
    redirect_to :controller => "service", :action => "facebook"
  end

  def delete_post
    @id = params[:post_id]
    @delete_post = params[:delete_post]
    @facebook.delete_object(@id)    
  end

  def facebook_return
  	redirect_to :controller => "service", :action => "facebook"
  end

end

app/controllers/user_controller.rb
	class UserController < ApplicationController
	before_filter :authenticate_user!

	def dashboard
	    @facebook ||= Koala::Facebook::API.new('CAACEdEose0cBACf74qX6YhtNDAmYKGhcArMOMBLADOgLDHOm2XDXCIZAZCZBCyGmkWBCZBvGAle6AohsQrYLEaiJZAyy0xlSaiPrS7ClIzkyZCJEhZChQA1nwz6ZAMSPYgZBomAKN3ebbzPeOHOXQEmAYKELUsYztN3bnoNcQj1ZBgOwZDZD')  
	    @notification = @facebook.fql_query("SELECT is_unread FROM notification WHERE recipient_id = me()").first
  		@not = @notification['is_unread']
  	end

 	def landing
  		render :dashboard
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_helper.rb
module ServiceHelper

def tweet
	
end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1374521139443218";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
</head>

<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Test Task app</a>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, :method => 'delete', :class => 'navbar-link'  %>
          <% else %>
           <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
    </div>
  </div>
</div>


<div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>  <%= flash[:notice] %></strong>
        </div>
      <% end %>
</div>









<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/service/block.html.erb
<div class="hero unit"
<h1> Blocked <%= @name %></h1>

app/views/service/facebook.html.erb
<h1 class="hero-unit center"> <img src="https://cdn1.iconfinder.com/data/icons/New-Social-Media-Icon-Set-V11/512/facebook.png" width="100px" height="100px"> Facebook
</h1>

<div>
	<hr>
	<h1>You have <%= @friends.first['friend_count']%> friends!! :) </h1>
	<br>
	<h3> Your recent posts...</h3>
	<br>
	<div class="hero-unit">
	<% @results.each do |result| %>
	<%=  result['message'] %>
	<%=  result['story'] %>
	<%= @id = result['id'] %>
	<br>
	<%= form_tag(:controller => "service" , :action => "like") do %>
			<%= hidden_field_tag(:post_id,@id) %>
  			<%= submit_tag("Like") %>
	<% end %>
	<%= form_tag(:controller => "service" , :action => "reply") do %>
			<%= hidden_field_tag(:post_id,@id) %>
			<%= label_tag(:q,"Comment") %>
			<%= text_field_tag(:reply_message) %>
  			<%= submit_tag("Reply") %>
	<% end %>
	<%= form_tag(:controller => "service" , :action => "delete_post") do %>
			<%= hidden_field_tag(:post_id,@id) %>
  			<%= submit_tag("Delete") %>
	<% end %>

	<br>
	<hr>
	<% end %>	
	</div>
</div>

app/views/service/twitter.html.erb
	<h1 class="hero-unit center"><img src="https://abs.twimg.com/a/1375391966/images/resources/twitter-bird-white-on-blue.png " width="100px" height="100px"> Twitter
		<ul>
			<br>	
			<li>
				<a href="https://twitter.com/intent/tweet?screen_name=current.user" class="twitter-mention-button" data-related="current.user">Tweet to @pallavi_shastry</a>
					<%= link_to "Search/hashtag","https://twitter.com/search-home", :class => "btn"%>	
			</li>
		</ul>
	</h1>

	<div class="brand" hero-unit>
			<div class="hero-unit span3 offset1">
				<h3>  Want to block a user ?Please provide the name </h3>	
					<%= form_tag(:controller => "service" , :action => "block") do %>
  						<%= label_tag(:q,"User Name") %>
 						<%= text_field_tag(:q) %>
  						<%= submit_tag("Block") %>
					<% end %>
			</div>

			<div class="hero-unit span3 offset6">
				<h3>Recent Tweets of <%= @twitter.first.user.name %></h3>		
				<% @twitter.each do |tweet| %>
				<br>
				<blockquote><%= tweet.text %></blockquote>
				<%= link_to "Reply","https://twitter.com/intent/tweet?screen_name=current.user", :class => "btn"%>
				<%= link_to "Retweet", "https://twitter.com/intent/retweet?tweet_id=#{tweet.id}", :class => "btn"%>
				<%= link_to "Favorite it" , "https://twitter.com/intent/favorite?tweet_id=#{tweet.id}" , :class =>"btn"%>
				<% end %>
				<br>
				<br>
			</div>
	</div>

 

app/views/user/dashboard.html.erb
<p class="text-center offset3 page-header brand"><h1>Social networks</h1>  </p>

<div class="hero-unit">
	
<div class='row-fluid dash-actions'>
  <%= link_to('auth/twitter',:class => 'btn btn-large btn-info') do %>
   <img src="https://abs.twimg.com/a/1375759071/images/resources/twitter-bird-blue-on-white.png" width="100px" height="100px">
   	 <% end %>
</div>

</div>


<div class="hero-unit">

	 
<div class='row-fluid dash-actions'>
  <%= link_to('auth/facebook',:class => 'btn btn-large btn-info') do %>
   <img src="https://cdn1.iconfinder.com/data/icons/New-Social-Media-Icon-Set-V11/512/facebook.png" width="100px" height="100px">
  <% end %>


  
<h3> <i> *</i> Notifications: <%= @not %></h3>
</div>

</div> 

app/views/user/landing.html.erb
<h1 class="page-header">Welcome to my test task app </h1>
<%= link_to 'Dashboard' ,user_dashboard_path %>